default: &default
  adapter: mysql2
  host: localhost
  username: root
  password: 
  socket: /tmp/mysql.sock
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: laraquette_dev

test:
  <<: *default
  database: laraquette_test

production:
  <<: *default
  database: laraquette_prod