default: &default
  adapter: mysql2
  host: 127.0.0.1
  username: root
  password: root
  pool: 5
  socket: /var/mysql/mysql.sock
  timeout: 5000
  port: 8889

development:
  <<: *default
  database: laraquette_dev

test:
  <<: *default
  database: laraquette_test

production:
  <<: *default
  database: laraquette_prod